use rand::Rng;
use serde::{Deserialize, Serialize};

use crate::link::Topology;
use crate::node::NodeState;
use crate::packet::{NodeId, Packet};

/// Traffic injection scenario types from the spec.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ScenarioType {
    Burst,
    Storm,
    LinkFail,
    NodeOverload,
    Cascade,
}

/// A parameterized traffic scenario.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Scenario {
    pub scenario_type: ScenarioType,
    pub source_node: NodeId,
    pub target_nodes: Vec<NodeId>,
    pub intensity: u32,
    pub duration_ticks: u32,
    pub remaining_ticks: u32,
}

impl Scenario {
    pub fn burst(source: NodeId, intensity: u32, duration: u32) -> Self {
        Self {
            scenario_type: ScenarioType::Burst,
            source_node: source,
            target_nodes: Vec::new(),
            intensity,
            duration_ticks: duration,
            remaining_ticks: duration,
        }
    }

    pub fn storm(sources: Vec<NodeId>, intensity: u32, duration: u32) -> Self {
        Self {
            scenario_type: ScenarioType::Storm,
            source_node: sources.first().cloned().unwrap_or_default(),
            target_nodes: sources,
            intensity,
            duration_ticks: duration,
            remaining_ticks: duration,
        }
    }

    pub fn link_fail(from: NodeId, to: NodeId, duration: u32) -> Self {
        Self {
            scenario_type: ScenarioType::LinkFail,
            source_node: from,
            target_nodes: vec![to],
            intensity: 0,
            duration_ticks: duration,
            remaining_ticks: duration,
        }
    }

    pub fn node_overload(node: NodeId) -> Self {
        Self {
            scenario_type: ScenarioType::NodeOverload,
            source_node: node,
            target_nodes: Vec::new(),
            intensity: 500,
            duration_ticks: 1,
            remaining_ticks: 1,
        }
    }

    pub fn cascade(source: NodeId, intensity: u32, duration: u32) -> Self {
        Self {
            scenario_type: ScenarioType::Cascade,
            source_node: source,
            target_nodes: Vec::new(),
            intensity,
            duration_ticks: duration,
            remaining_ticks: duration,
        }
    }

    pub fn is_active(&self) -> bool {
        self.remaining_ticks > 0
    }

    pub fn tick(&mut self) {
        if self.remaining_ticks > 0 {
            self.remaining_ticks -= 1;
        }
    }
}

/// Manages active scenarios and applies their effects each tick.
pub struct ScenarioEngine {
    pub active_scenarios: Vec<Scenario>,
}

impl ScenarioEngine {
    pub fn new() -> Self {
        Self {
            active_scenarios: Vec::new(),
        }
    }

    pub fn inject(&mut self, scenario: Scenario) {
        self.active_scenarios.push(scenario);
    }

    /// Apply all active scenarios for this tick.
    /// Returns packets generated by scenarios.
    pub fn apply_tick(
        &mut self,
        nodes: &mut Vec<NodeState>,
        topology: &mut Topology,
        tick: u64,
    ) -> Vec<Packet> {
        let mut generated_packets = Vec::new();
        let mut rng = rand::thread_rng();

        for scenario in &mut self.active_scenarios {
            if !scenario.is_active() {
                continue;
            }

            match scenario.scenario_type {
                ScenarioType::Burst => {
                    // Generate burst packets from source node
                    let all_ids: Vec<NodeId> = nodes.iter().map(|n| n.id.clone()).collect();
                    for _ in 0..scenario.intensity {
                        let dest_idx = rng.gen_range(0..all_ids.len());
                        if all_ids[dest_idx] != scenario.source_node {
                            generated_packets.push(Packet::new(
                                scenario.source_node.clone(),
                                all_ids[dest_idx].clone(),
                                1024,
                                rng.gen_range(0..4),
                                tick,
                            ));
                        }
                    }
                }
                ScenarioType::Storm => {
                    // Synchronized multi-node flood
                    let all_ids: Vec<NodeId> = nodes.iter().map(|n| n.id.clone()).collect();
                    let storm_sources = if scenario.target_nodes.is_empty() {
                        all_ids.clone()
                    } else {
                        scenario.target_nodes.clone()
                    };
                    for src in &storm_sources {
                        for _ in 0..scenario.intensity {
                            let dest_idx = rng.gen_range(0..all_ids.len());
                            if &all_ids[dest_idx] != src {
                                generated_packets.push(Packet::new(
                                    src.clone(),
                                    all_ids[dest_idx].clone(),
                                    1024,
                                    rng.gen_range(0..4),
                                    tick,
                                ));
                            }
                        }
                    }
                }
                ScenarioType::LinkFail => {
                    if let Some(target) = scenario.target_nodes.first() {
                        if let Some(link) = topology.get_link_mut(&scenario.source_node, target) {
                            link.fail();
                        }
                    }
                }
                ScenarioType::NodeOverload => {
                    if let Some(node) = nodes.iter_mut().find(|n| n.id == scenario.source_node) {
                        let remaining = node.queue_capacity.saturating_sub(node.queue_depth);
                        for _ in 0..remaining {
                            let pkt = Packet::new(
                                node.id.clone(),
                                node.id.clone(),
                                512,
                                0,
                                tick,
                            );
                            node.enqueue(pkt, tick as f64);
                        }
                    }
                }
                ScenarioType::Cascade => {
                    // Generate heavy traffic that will cascade through the network
                    let all_ids: Vec<NodeId> = nodes.iter().map(|n| n.id.clone()).collect();
                    // Target the farthest nodes to force multi-hop cascading
                    for dest in &all_ids {
                        if dest != &scenario.source_node {
                            for _ in 0..(scenario.intensity / all_ids.len() as u32).max(1) {
                                generated_packets.push(Packet::new(
                                    scenario.source_node.clone(),
                                    dest.clone(),
                                    2048,
                                    3,
                                    tick,
                                ));
                            }
                        }
                    }
                }
            }

            scenario.tick();
        }

        // Restore links from expired link_fail scenarios
        let expired_link_fails: Vec<(NodeId, Vec<NodeId>)> = self
            .active_scenarios
            .iter()
            .filter(|s| {
                !s.is_active() && matches!(s.scenario_type, ScenarioType::LinkFail)
            })
            .map(|s| (s.source_node.clone(), s.target_nodes.clone()))
            .collect();

        for (from, targets) in expired_link_fails {
            for to in targets {
                if let Some(link) = topology.get_link_mut(&from, &to) {
                    link.restore();
                }
            }
        }

        // Remove expired scenarios
        self.active_scenarios.retain(|s| s.is_active());

        generated_packets
    }
}
